### ISSUE TITLE
Descriptions of fields

### ISSUE THREAD

**Issue by hbarrett** [imls-dmt/imls-dmt-api#11]
Please provide descriptions for all fields in the resources schema .
/api/schema/resources.html

**Comment by njhoebel** [comment]
For several days, I have been unable to resolve the resources.html URL above;  get an "internal server error" with text as follows:
"The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at root@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log."

Want to verify that I have all of the names of all the fields that need descriptions / definitions.
