### ISSUE TITLE
Differing uses of author field

### ISSUE THREAD

**Issue by njhoebel** [imls-dmt/imls-dmt-api#12]
In the schema derived from drupal, there is an "author" field that turns out to be used within drupal as the creator of the record describing the content rather than the author of the content which is the way that term was used when it appeared in the Submission form.  Consequently, the values that show up in the author field within the database only map to the content author when the value of the "contact" field is the same.  This has resulted in (bib sense of) content authors not showing up in searches for them as authors unless they were also listed as contacts.  Second & third (etc.) authors do now show up as authors at all when searching for them by name.  Hopefully, this can be rectified in the new DB structure.  

Further background info:  Also in drupal, there is a "group_authors" field which acts as a container for all the subfields of personal names and organization authors, and which might be the source of the information for the search results which _do_ display the author(s) of the content in the full display of the record.  See the google sheet at:  https://docs.google.com/spreadsheets/d/1c3Q9Lq0J08Vqk3nV6alOP-qtO8LZ06dMfE9wj3PoLlI/edit#gid=325723660 for further info.  

Might also be better to treat these personal names the same way that the schema (non-drupal) treats contributor names for persons which is to separate first and last names.

**Comment by hbarrett** [comment]
changed author to creator then added resource author.
