### ISSUE TITLE
Adding existing and potential for new education framework nodes

### ISSUE THREAD

**Issue by njhoebel** [imls-dmt/imls-dmt-api#13]
There need to be more fields for each of the educational frameworks that have nodes associated with them now, and also have the capacity to add them in the future.  Currently, we have ed_framework_fair and ed_framework_dataone, but we also need fields for esip short course and for usgs.   These fields contain the list of nodes for each of the frameworks within them.

**Comment by hbarrett** [comment]
Frameworks are now represented as nested objects:

```
ed_frameworks": [
        {
          "name": "DataONE Education Modules",
          "nodes": [
            "Analyze",
            "Assure",
            "Collect",
            "Describe",
            "Discover",
            "Integrate",
            "Plan",
            "Preserve"
          ]
        },
        {
          "name": "FAIR Data Principles",
          "nodes": [
            
          ]
        }
      ]
```
