### ISSUE TITLE
Change name of "persistent_personal_identifier" and "personal_identifier_type" in the schema.

### ISSUE THREAD

**Issue by njhoebel** [imls-dmt/imls-dmt-api#28]
persistent_personal_identifier changed to "name_identifier"
personal_identifier_type changed to "name_identifier_type"

That way, these two fields can be used for both persons and organizations.

**Comment by hbarrett** [comment]
Verify search works.

**Comment by hbarrett** [comment]
These would be keys in authors, contributors, contributor_orgs 
"author_org" needs to be an array of objects with keys "name","name_identifier" and "name_identifier_type"
examples:
"author_org": {"name":"Australian National Data Service (ANDS)",
 "name_identifier":"",
"name_identifier_type":""}

"authors": [
        {
          "familyName": "Smith", 
          "givenName": "Colin",
        "name_identifier":"",
        "name_identifier_type":""
        }, 
        {
          "familyName": "Grossman-Clarke", 
          "givenName": "Susanne ",
 "name_identifier":"",
"name_identifier_type":""
        }
      ],
