### ISSUE TITLE
Rename "target_description" to "ed_frameworks.nodes.description and 

### ISSUE THREAD

**Issue by njhoebel** [imls-dmt/imls-dmt-api#35]

**Comment by njhoebel** [comment]
This will make it easier to keep track of what these fields are about, i.e., ed frameworks rather than target audience.

**Comment by hbarrett** [comment]
Example:
"ed_frameworks": [
        {
          "name": "ESIP Data Management for Scientists Short Course", 
          "nodes": [
            {"description":"","name":"Local Data Management","url":""}
         
          ]
        }
      ],

**Comment by njhoebel** [comment]
what came after the "and" in the name of the issue was ""target_url" to "ed_frameworks.nodes.url".
