### ISSUE TITLE
Create resources result JSON that only summarizes results

### ISSUE THREAD

**Issue by karlbenedict** [imls-dmt/imls-dmt-api#49]
For a lightweight initial load of Clearinghouse content create a result/search option that allows the user to essentially get the summary results of a query - essentially the header info

```
{
    "documentation": "https://esip-dev-02.edacnm.org/api/resources/documentation.html",
    "facets": ⊕{...},
    "hits-returned": 10,
    "hits-total": 15,
}
```

plus a list of the `id`s for the found items.

**Comment by hbarrett** [comment]
Requests now support summary queries:

GET: /api/resources/?summary=True

POST:
```
{
  "search": [ ],
"summary":true
}
```
