### ISSUE TITLE
return authenticated user type with token 

### ISSUE THREAD

**Issue by karlbenedict** [imls-dmt/imls-dmt-api#64]
To enable client developer to customize user interface based on authenticated user type, return the user type with the token. This would allow the client to read the content of the cookie and customize the user interface accordingly.

**Comment by hbarrett** [comment]
Would this work? 
https://esip-dev-02.edacnm.org/user/groups

An empty array like `{"groups": []}` means the user is not logged in.

**Comment by karlbenedict** [comment]
I expect that that would work.
