### ISSUE TITLE
Add an RSS feed for resources to the API

### ISSUE THREAD

**Issue by karlbenedict** [imls-dmt/imls-dmt-api#66]
It would be useful to have an RSS feed (https://validator.w3.org/feed/docs/rss2.html) for recently added resources available as a call from the API.

**Comment by hbarrett** [comment]
https://esip-dev-02.edacnm.org/rss

**Comment by karlbenedict** [comment]
This looks great. Is this based on all of the recently added, or only published resources? I now realize that I should have been more clear in the initial issue - it should be limited to recently published items.

**Comment by hbarrett** [comment]
It is only published. Solr query "status:True"

**Comment by hbarrett** [comment]
If author_names
elseif author_org.name
else "Unknown"

**Comment by hbarrett** [comment]
RSS is working as expected.
