### ISSUE TITLE
For "author_org" facet return org phrase and not individual tokens

### ISSUE THREAD

**Issue by karlbenedict** [imls-dmt/imls-dmt-api#67]
The "author_org" listing includes frequencies of the individual tokens (words) in the organization names instead of full organization names as provided in the metadata in 

`author_org:{name:" long name ", ...}`

Add to facets as `author_org_name`

**Comment by hbarrett** [comment]
re-index by duplicating it and changing the type of field from type="text_general" into type="string"

**Comment by hbarrett** [comment]
For consistency it is now named author_org.name
This is due to the author_org being stored as an object with the format: `{"name":"","name_identifier":"","name_identifier_type":""}`
