### ISSUE TITLE
return options with stored case in metadata template

### ISSUE THREAD

**Issue by karlbenedict** [imls-dmt/imls-dmt-api#72]
The values being returned in options lists for form controls are currently being returned in lowercase. We need to carry mixed case through the round-trip from controlled / reference list to the interface and back into the metadata.

**Comment by hbarrett** [comment]
Facets are showing as lower case for authors.familyName and others. These should all be mixed cases.

**Comment by hbarrett** [comment]
This appears (from trial and error) to be due to the combination of this field being facet field, text_general and multivalued in the solr schema. I switched the type from text_general to string, and it appears to show up with uppercases now.

**Comment by hbarrett** [comment]
Resolved.
