### ISSUE TITLE
Shared picklists for different fields

### ISSUE THREAD

**Issue by karlbenedict** [imls-dmt/imls-dmt-api#73]
the following fields should use a shared picklist: all of these should be datalist fields

author_givenName, contributors__givenName 
author_familyName, contributors__familyName
author_orgName, contributor_orgs__Name

**Comment by hbarrett** [comment]
contributors__givenName, contributors__familyName should use facets from author_givenName, and author_familyName.
contributors__givenName, contributors__familyName should be faceted and both of these facets should be combined to be used as the picklist for each givenName and familyName.


contributor_orgs.name should use the same list as author_org.name.
contributor_orgs.name should be faceted and combined with author_org.name and used for picklist of both.
